#!/bin/sh
# hig-pr: open a pull request in github or bitbucket
# usage: hig pr [<base-branch>]

. "$_HIG_LIB_PATH/common.sh"

if [ "$1" = "-h" ]; then
    fatal "usage: hig pr [<base-branch>]"
fi

fmt=`hig format`
if [ "${fmt}" != git ]; then
    fatal "pr: only supports git repos"
fi

base="$1"
shift || :
if [ -z "${base}" ]; then
    base=master
fi
debug base=$base

remote_name="$(git config branch.${base}.remote)"
if [ -z "${remote_name}" ]; then
    remote_name=origin
fi
debug remote_name=$remote_name

remote_url="$(git config remote.${remote_name}.url)"
debug remote_url=$remote_url
if [ -z "${remote_url}" ]; then
    fatal "pr: could not determine url for remote: ${remote_name}"
fi

# $head is the branch we want to apply to $base
head="$(git_head)"
debug head=$head
remote_host="$(git_host_from_repo_url ${remote_url})"
debug remote_host=$remote_host
remote_owner="$(git_owner_from_repo_url ${remote_url})"
debug remote_owner=$remote_owner
remote_repo="$(git_repo_from_repo_url ${remote_url})"
debug remote_repo=$remote_repo

title="$(git show  -s --format=%s)"
message="$(git show  -s --format=%B)"

case "${remote_host}" in
    github.com )
        if ! command -v hub >/dev/null; then
            fatal "pr: could not find hub(1); Check https://hub.github.com/ for how to install"
        fi
        hig push
        debug exec hub pull-request -m \"${message}\" -b \"${remote_owner}/${remote_repo}:${base}\" -h \"${head}\"
        exec hub pull-request -m "${title}" -b "${remote_owner}:${base}" -h "${head}"
        ;;
    bitbucket.org )
        if ! command -v bitbucket >/dev/null; then
            fatal "pr: could not find bitbucket(1); Check https://bitbucket.org/zhemao/bitbucket-cli for how to install"
        fi
        hig push
        debug exec bitbucket pull_request --owner \"${remote_owner}\" --reponame \"${remote_repo}\" --title \"${title}\" \"${head}\" \"${base}\"
        exec bitbucket pull_request --owner "${remote_owner}" --reponame "${remote_repo}" --title "${title}" "${head}" "${base}"
        ;;
    * )
        fatal "pr: couldn't recognize remote url: ${remote_url}"
        ;;
esac
