#!/bin/sh
# hig-get: get remote repo
# usage: hig get <repo>

. "$_HIG_LIB_PATH/common.sh"

REPO="$1"
shift

if command -v hg >/dev/null &&
  debug " hg identify  ${REPO}" &&  hg identify  "${REPO}" >/dev/null; then
    CMD="hg clone"
elif command -v git >/dev/null &&
  debug "git ls-remote ${REPO}" && git ls-remote "${REPO}" >/dev/null; then
    CMD="git clone"
elif command -v darcs >/dev/null &&
  debug "attempting darcs" && curl -sf "${REPO}/_darcs/format" >/dev/null; then
    CMD="darcs get"
elif command -v svn >/dev/null &&
  debug "svn info --non-interactive --trust-server-cert ${REPO}" && 
    svn info --non-interactive --trust-server-cert "${REPO}" >/dev/null; then
  # debug "svn info      ${REPO}" && svn info --non-interactive --trust-server-cert "${REPO}" >/dev/null; then
    CMD="svn checkout"
else
    echo "Unknown repo format: $REPO" >&2
    exit 1
fi

exec $CMD "$REPO" "$@"
