#!/bin/sh
# hig-diff: show diff between current files and last version
# usage: hig diff [<ref> [<file>...]]

. "$_HIG_LIB_PATH/common.sh"

fmt=`hig format`
case $fmt in
git )
  CMD="git diff"
  ;;
hg )
  CMD="hg diff --git"
  ;;
svn )
  CMD="svn diff --git"
  ;;
* )
  fatal "diff: unknown command for repo type: $fmt"
  ;;
esac

# sccsdiff

exec $CMD "$@"
