- docker package build from https://github.com/nolo-metrics/nolo-librato/commit/c4c87f9812ebda8cc3c84945ca5dd59097bd7f88
- can we bring this into the repo? https://github.com/josephholsten/homebrew-josephholsten/blob/master/hig.rb
