#!/bin/sh
# hig-diff: show diff between current files and last version

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git diff"
  ;;
svn )
  CMD="svn diff --git"
  ;;
hg )
  CMD="hg diff --git"
  ;;
* )
  fatal "diff: unknown command for repo type: `hig format`"
  ;;
esac

# sccsdiff

exec $CMD "$@"
