#!/bin/sh
# hig-mktag: make new tag

. $_HIG_ROOT/lib/common.sh

TAG=`shift`

case `hig format` in
git )
  CMD="git tag ${TAG}"
  ;;
hg )
  CMD="hg tag ${TAG}"
  ;;
bzr )
  CMD="bzr tag ${TAG}"
  ;;
* )
  fatal "mktag: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
