#!/bin/sh
# hig-chbr: change active branch

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git checkout"
  ;;
hg )
  CMD="hg checkout"
  ;;
svn )
  fatal "chbr: Subversion checkout is probably not what you want"
  ;;
* )
  fatal "chbr: unknown command for repo type: `hig format"
  ;;
esac

exec $CMD "$@"
