#!/bin/sh
# hig-add: add file to versioned files

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git add"
  ;;
svn )
  CMD="svn add"
  ;;
hg )
  CMD="hg add"
  ;;
* )
  fatal "add: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
