#!/bin/sh
# hig-push: push changes to remote repo
# usage: hig push [<repo>]

. "$_HIG_ROOT/lib/common.sh"

fmt=`hig format`
case $fmt in
git )
  CMD="git push --quiet"
  ;;
hg )
  CMD="hg push"
  ;;
svn )
  echo THIS IS NOT WHAT YOU WANT >&2
  exit -1
  ;;
* )
  fatal "push: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
