#!/bin/sh
# supported formats: git, hg, bzr, svn, darcs

if which git >/dev/null &&
    git status >/dev/null 2>&1; then
  echo git
  exit
elif which svn >/dev/null &&
    svn info >/dev/null 2>&1; then
  echo svn
  exit
elif which hg >/dev/null &&
    hg status >/dev/null 2>&1; then
  echo hg
  exit
elif which bzr >/dev/null &&
    bzr info >/dev/null 2>&1; then
  echo bzr
  exit
elif which cvs >/dev/null &&
    test -x CVS &&
    cvs st  >/dev/null 2>&1; then
  echo bzr
else
  echo Unknown repo format >&2
  exit -1
fi
