#!/bin/sh
# hig-lsbr: list branches

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git branch"
  ;;
hg )
  CMD="hg branches"
  ;;
* )
  fatal "lsbr: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
