#!/bin/sh
# hig-mkbr: make new branch

. $_HIG_ROOT/lib/common.sh

BRANCH=`shift`

fmt=`hig format`
case $fmt in
git )
  CMD="git checkout -b ${BRANCH}"
  ;;
hg )
  CMD="hg branch ${BRANCH}"
  ;;
bzr )
  CMD="bzr branch --switch ${BRANCH}"
  ;;
* )
  fatal "mkbr: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
