#!/bin/sh
# hig-mktag: make new tag

. $_HIG_ROOT/lib/common.sh

TAG=`shift`

fmt=`hig format`
case $fmt in
git )
  CMD="git tag --quiet ${TAG}"
  ;;
hg )
  CMD="hg tag ${TAG}"
  ;;
bzr )
  CMD="bzr tag ${TAG}"
  ;;
* )
  fatal "mktag: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
