#!/bin/sh
# hig-rebase: ...

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
git )
  CMD="git rebase"
  ;;
* )
  fatal "rebase: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
