#!/bin/sh
# hig-ci: commit changes to version history

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
git )
  CMD="git commit -a"
  ;;
svn )
  CMD="svn commit"
  ;;
hg )
  CMD="hg commit"
  ;;
* )
  fatal "ci: unknown command for repo type: $fmt"
  ;;
esac

debug CMD=$CMD

exec $CMD "$@"
