#!/bin/sh
# hig-lsbr: list branches

. $_HIG_ROOT/lib/common.sh

BRANCH=`shift`

case `hig format` in
git )
  CMD="git branch -d ${BRANCH}"
  ;;
* )
  fatal "rmbr: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
