#!/bin/sh
# hig-add: add file to versioned files

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
git )
  CMD="git add"
  ;;
svn )
  CMD="svn add"
  ;;
hg )
  CMD="hg add"
  ;;
* )
  fatal "add: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
