#!/bin/sh
# hig-push: push changes to remote repo

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git push --quiet"
  ;;
hg )
  CMD="hg push"
  ;;
svn )
  echo THIS IS NOT WHAT YOU WANT >&2
  exit -1
  ;;
* )
  fatal "push: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
