#!/bin/sh
# hig-st: show repo status

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git status"
  ;;
svn )
  CMD="svn status"
  ;;
hg )
  CMD="hg status"
  ;;
* )
  fatal "st: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
