#!/bin/sh

echo "usage: hig <cmd> [<args>]"
echo "  commands:"
echo "  get   retrieve a repository into a new directory"
echo "  add   add the specified files on the next commit"
echo "  rm    remove the specified files on the next commit"
echo "  mv    rename files"
echo "  ci    commit the specified files or all outstanding changes"
echo "  st    show changed files in the working directory"
echo "  co    checkout working directory (or switch revisions)"
echo "  diff  show file differences"
echo "  log   show revision history"
echo "  pull  pull changes from the specified source"
echo "  push  push changes to the specified destination"
exit -1
