#!/bin/sh
# hig-get: get remote repo
# usage: hig get <repo>

. "$_HIG_ROOT/lib/common.sh"

REPO=$1
shift

if expr $REPO : ".*\.git" >/dev/null; then
  CMD="git clone"
elif expr $REPO : "git:.*" >/dev/null; then
  CMD="git clone"
elif expr $REPO : ":pserver:.*" > /dev/null; then
  export CVSREPO=$REPO
  CMD="cvs co"
elif expr $REPO : "http.*" >/dev/null; then
  debug 'http: repo'
  if debug 'attempting darcs' && curl -sf $REPO/_darcs/format >/dev/null; then
    CMD="darcs get"
  elif debug 'attempting git' && curl -sf "${REPO}.git/info/refs?service=git-upload-pack" >/dev/null; then
    CMD="git clone"
  elif debug 'attempting svn' && svn info --non-interactive --trust-server-cert $REPO >/dev/null; then
    CMD="svn checkout"
  elif debug 'attempting hg' && curl -sf "$REPO?cmd=lookup&key=tip" >/dev/null; then
    CMD="hg clone"
  fi
else
  echo "Unknown repo format: $REPO" >&2
  exit 1
fi

exec $CMD $REPO "$@"
