#!/bin/sh
# hig-st: show repo status

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
git )
  CMD="git status"
  ;;
svn )
  CMD="svn status"
  ;;
hg )
  CMD="hg status"
  ;;
* )
  fatal "st: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
