#!/bin/sh
# hig-co: checkout files from a seperate branch

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git checkout"
  ;;
hg )
  CMD="hg checkout"
  ;;
svn )
  fatal "co: Subversion checkout is probably not what you want"
  ;;
* )
  fatal "co: unknown command for repo type: `hig format"
  ;;
esac

exec $CMD "$@"
