#!/bin/sh
# hig-lstag: list tags

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git tag --all"
  ;;
hg )
  CMD="hg tags"
  ;;
bzr )
  CMD="bzr tags"
  ;;
* )
  fatal "Unknown repo format"
  ;;
esac

exec $CMD "$@"
