#!/bin/sh

case `hig format` in
git )
  CMD="git log"
  ;;
svn )
  CMD="svn log"
  ;;
hg )
  CMD="hg log"
  ;;
* )
  fatal "log: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
