#!/bin/sh
# hig-pick: cherry pick a single patch

. $_HIG_ROOT/lib/common.sh

REF=`shift`

case `hig format` in
git )
  CMD="git cherry-pick ${REF}"
  ;;
* )
  fatal "pick: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
