#!/bin/sh
# hig-pull: pull changes from remote repository

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git pull"
  ;;
svn )
  CMD="svn update"
  ;;
hg )
  CMD="hg pull -u"
  ;;
* )
  fatal "pull: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
