#!/bin/sh
# hig-log: list revision history

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
git )
  CMD="git log"
  ;;
svn )
  CMD="svn log"
  ;;
hg )
  CMD="hg log"
  ;;
* )
  fatal "log: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
