#!/bin/sh

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git commit -a"
  ;;
svn )
  CMD="svn commit"
  ;;
hg )
  CMD="hg commit"
  ;;
* )
  fatal "unknown repo format"
esac

debug CMD=$CMD

exec $CMD "$@"
