#!/bin/sh
# hig-rm - remove file from version control, leaving the
# existing contents on disk

. $_HIG_ROOT/lib/common.sh

case `hig format` in
git )
  CMD="git rm"
  ;;
svn )
  CMD="svn delete --keep-local"
  ;;
hg )
  CMD="hg remove --after --force"
  ;;
* )
  fatal "rm: unknown command for repo type: `hig format`"
  ;;
esac

exec $CMD "$@"
