#!/bin/sh
# hig-lstag: list tags

. $_HIG_ROOT/lib/common.sh

fmt=`hig format`
case $fmt in
bzr )
  CMD="bzr tags"
  ;;
git )
  CMD="git tag"
  ;;
hg )
  CMD="hg tags"
  ;;
* )
  fatal "lstag: unknown command for repo type: $fmt"
  ;;
esac

exec $CMD "$@"
