#!/bin/sh
# hig - revision control, wrapped to behave identically for git, hg, svn, darcs & bzr
# Provides get, add, rm, mv, ci, st, co, diff, push, pull.
# Usually symlinked to provide ci, st, co, push & pull as standalone commands
set -e
if [ -n "$TRACE" ]; then
	set -x
fi

log() {
  echo "$@" >&2
}

debug() {
  if [ -n "$DEBUG" ] || [ -n "$TRACE" ]; then
    log "$@"
  fi
}

trace() {
  if [ -n "$TRACE" ]; then
    log "$@"
  fi
}

fatal() {
  log "$@"
  exit 1
}

# return the target of a symbolic link
resolve_link() {
  READLINK=readlink
  if [ -n "$(command -v greadlink >/dev/null 2>&1)" ]; then
    READLINK=greadlink
  fi
  $READLINK "$1"
}

# return the cannonical directory containing a file
abs_dirname() {
  local cwd="$(pwd)"
  trace cwd=$cwd
  local path="$1"
  trace path=$path

  while [ -n "$path" ]; do
    local nextdir="$(dirname "$path")"
    trace nextdir=$nextdir
    cd "$nextdir"
    local name="$(basename "$path")"
    trace name=$name
    path="$(resolve_link "$name" || true)"
    trace path=$path
  done

  trace pwd=$(pwd)
  pwd
  cd "$cwd"
}

# add our libexec to PATH
debug '$0'=$0
_HIG_LIBEXEC_PATH="$(abs_dirname "$0")"
debug _HIG_LIBEXEC_PATH=$_HIG_LIBEXEC_PATH
export PATH="${_HIG_LIBEXEC_PATH}:$PATH"

# child, always remember where you came from
export _HIG_LIB_PATH="$(abs_dirname "$(abs_dirname "$_HIG_LIBEXEC_PATH")")/lib/hig"
debug _HIG_LIB_PATH=$_HIG_LIB_PATH

# allow being called as `hig foo` or just `foo`
base=$(basename "$0")
debug base=$base
if [ "$base" = "hig" ]; then
  command="$1"
  if [ "$#" != "0" ]; then
    shift
  fi
else
  command="$base"
fi
debug command=$command

case "$command" in
"" | "hig" | "-h" | "--help" )
  exec hig-help
  ;;
* )
  command_path="$(command -v "hig-$command" || true)"
  debug command_path="$command_path"
  if [ ! -x "$command_path" ]; then
    fatal "hig: no such command \`$command'"
  fi

  debug exec "$command_path" "$@"
  exec "$command_path" "$@"
  ;;
esac
